### PR TITLE
Add regional and administrative French Republic subdivision

### PR DESCRIPTION
**Pull request by remi-georges**

### CODE REVIEW

**Comment by LaurentVB** [comment]
Hey @remi-georges , thanks for the PR. 
Can you provide some reference for these specs? A link to an official source in the comment would be ok.

**Comment by thibaultyou** [comment]
Hey there, you can find french regional country codes on [ISO 13616-Compliant IBAN Formats](https://www.swift.com/sites/default/files/resources/iban_registry.pdf) provided by SWIFT at page 32

**Comment by LaurentVB** [comment]
Excellent, thanks 👍

**Comment by LaurentVB** [comment]
Released in v0.0.14

**Pull request merged**
